// xiaoxiao

#pragma once
#include "NativeGameplayTags.h"


namespace warriorTag {

	WARRIOR_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Move)
	WARRIOR_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Look)
	
	WARRIOR_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Equine_Axe)
	WARRIOR_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Weapons_Axe)

	WARRIOR_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Equip_Axe)
	WARRIOR_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_NonEquip_Axe)
	WARRIOR_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Equine_Axe)
	WARRIOR_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_NonEquine_Axe)
	
}


